// <auto-generated />
using System;
using Dotnetable.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dotnetable.Migrations.MySql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Dotnetable.Domain.Entities.City", b =>
                {
                    b.Property<int>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<double?>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<int?>("StateID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("varchar(48)");

                    b.HasKey("CityID");

                    b.HasIndex("CountryID");

                    b.HasIndex("StateID");

                    b.ToTable("City", (string)null);
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.CityTranslation", b =>
                {
                    b.Property<int>("CityTranslationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("varchar(48)");

                    b.HasKey("CityTranslationID");

                    b.HasIndex("CityID");

                    b.ToTable("CityTranslation", (string)null);
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.ContactUsMessage", b =>
                {
                    b.Property<int>("ContactUsMessagesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CellphoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("datetime");

                    b.Property<string>("MessageBody")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("MessageSubject")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("SenderIPAddress")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("ContactUsMessagesID");

                    b.ToTable("ContactUsMessage", (string)null);
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.Country", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("PhonePerfix")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("varchar(42)");

                    b.HasKey("CountryID");

                    b.ToTable("Country", (string)null);
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.CountryTranslation", b =>
                {
                    b.Property<int>("CountryTranslationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("varchar(42)");

                    b.HasKey("CountryTranslationID");

                    b.HasIndex("CountryID");

                    b.ToTable("CountryTranslation", (string)null);
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.EmailSetting", b =>
                {
                    b.Property<int>("EmailSettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DefaultEMail")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<byte>("EmailTypeID")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("EnableSSL")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MailName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("MailServer")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("SMTPPort")
                        .HasColumnType("int");

                    b.HasKey("EmailSettingID");

                    b.ToTable("EmailSetting", (string)null);
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.EmailSubscribe", b =>
                {
                    b.Property<int>("EmailSubscribeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Approved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("MemberID")
                        .HasColumnType("int");

                    b.HasKey("EmailSubscribeID");

                    b.HasIndex("MemberID");

                    b.ToTable("EmailSubscribe", (string)null);
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.FileRecord", b =>
                {
                    b.Property<int>("FileRecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AltText")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("CDNFileCode")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("CNDUrl")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<byte>("FileCategory")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("FileSizeKB")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MetadataJSON")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(74)
                        .IsUnicode(false)
                        .HasColumnType("varchar(74)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(350)
                        .HasColumnType("varchar(350)");

                    b.Property<short>("StorageProvider")
                        .HasColumnType("smallint");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("ThumbnailCDN")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("ThumbnailStorage")
                        .HasMaxLength(350)
                        .HasColumnType("varchar(350)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime");

                    b.Property<int>("WebsiteStorageSettingsID")
                        .HasColumnType("int");

                    b.HasKey("FileRecordID");

                    b.HasIndex("WebsiteStorageSettingsID");

                    b.ToTable("FileRecord", (string)null);
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.Language", b =>
                {
                    b.Property<int>("LangaugeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("LanguageCodeISO")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<bool>("RTLDesign")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("WebsiteID")
                        .HasColumnType("int");

                    b.HasKey("LangaugeID");

                    b.HasIndex("WebsiteID");

                    b.ToTable("Language", (string)null);
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.LocalizationKey", b =>
                {
                    b.Property<int>("LocalizationKeyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasMaxLength(72)
                        .IsUnicode(false)
                        .HasColumnType("varchar(72)");

                    b.Property<int>("WebsiteID")
                        .HasColumnType("int");

                    b.HasKey("LocalizationKeyID");

                    b.HasIndex("WebsiteID");

                    b.ToTable("LocalizationKey", (string)null);
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.LocalizationValue", b =>
                {
                    b.Property<int>("LocalizationValueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ItemValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<int>("LocalizationKeyID")
                        .HasColumnType("int");

                    b.HasKey("LocalizationValueID");

                    b.HasIndex("LocalizationKeyID");

                    b.ToTable("LocalizationValue", (string)null);
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.LoginTry", b =>
                {
                    b.Property<int>("LoginTryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("datetime");

                    b.Property<string>("TryIP")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.HasKey("LoginTryID");

                    b.ToTable("LoginTry", (string)null);
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("AvatarID")
                        .HasColumnType("char(36)");

                    b.Property<string>("CellphoneNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Givenname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid>("HashKey")
                        .HasColumnType("char(36)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("PolicyID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("RegisterDate")
                        .HasColumnType("date");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("WebsiteID")
                        .HasColumnType("int");

                    b.HasKey("MemberID");

                    b.HasIndex("PolicyID");

                    b.HasIndex("WebsiteID");

                    b.ToTable("Member", (string)null);
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.MemberForgetPassword", b =>
                {
                    b.Property<int>("MemberForgetPasswordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ForgetKey")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("datetime");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.HasKey("MemberForgetPasswordID");

                    b.HasIndex("MemberID");

                    b.ToTable("MemberForgetPassword", (string)null);
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.Policy", b =>
                {
                    b.Property<int>("PolicyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.HasKey("PolicyID");

                    b.ToTable("Policy", (string)null);
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.PolicyRole", b =>
                {
                    b.Property<int>("PolicyRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PolicyID")
                        .HasColumnType("int");

                    b.Property<short>("RoleID")
                        .HasColumnType("smallint");

                    b.HasKey("PolicyRoleID");

                    b.HasIndex("PolicyID");

                    b.HasIndex("RoleID");

                    b.ToTable("PolicyRole", (string)null);
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.Role", b =>
                {
                    b.Property<short>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("RoleKey")
                        .IsRequired()
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("varchar(42)");

                    b.HasKey("RoleID");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.State", b =>
                {
                    b.Property<int>("StateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("Tile")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("varchar(48)");

                    b.HasKey("StateID");

                    b.HasIndex("CountryID");

                    b.ToTable("State", (string)null);
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.StateTranslation", b =>
                {
                    b.Property<int>("StateTranslationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<int>("StateID")
                        .HasColumnType("int");

                    b.Property<string>("Tile")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("varchar(48)");

                    b.HasKey("StateTranslationID");

                    b.HasIndex("StateID");

                    b.ToTable("StateTranslation", (string)null);
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.Website", b =>
                {
                    b.Property<int>("WebsiteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowAllIP")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("AuthCode")
                        .HasColumnType("char(36)");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasComment("show in title of pages");

                    b.Property<string>("DefaultLanguageCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<int?>("FaveIconFileID")
                        .HasColumnType("int");

                    b.Property<int?>("LogoFileID")
                        .HasColumnType("int");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<DateOnly>("RegisterDate")
                        .HasColumnType("date");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("WebsiteAddress")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<byte>("WebsiteType")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("WebsiteID");

                    b.HasIndex("FaveIconFileID");

                    b.HasIndex("LogoFileID");

                    b.ToTable("Website", (string)null);
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.WebsiteIP", b =>
                {
                    b.Property<int>("WebsiteIPID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("CidrPrefix")
                        .HasColumnType("int");

                    b.Property<string>("EndIP")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("StartIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<int>("WebsiteID")
                        .HasColumnType("int");

                    b.HasKey("WebsiteIPID");

                    b.HasIndex("WebsiteID");

                    b.ToTable("WebsiteIP", (string)null);
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.WebsiteScript", b =>
                {
                    b.Property<int>("WebsiteScriptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte?>("Priority")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<byte>("ScriptLoadCondition")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("ScriptPosition")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("WebsiteID")
                        .HasColumnType("int");

                    b.HasKey("WebsiteScriptID");

                    b.HasIndex("WebsiteID");

                    b.ToTable("WebsiteScript", (string)null);
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.WebsiteSeoSetting", b =>
                {
                    b.Property<int>("WebsiteSeoSettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CustomRobotsTxt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DefaultMetaDescription")
                        .HasMaxLength(158)
                        .HasColumnType("varchar(158)");

                    b.Property<string>("DefaultMetaTitle")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasComment("Page | {SiteName}");

                    b.Property<bool>("RobotsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SitemapEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TitleSeparator")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasDefaultValue(" | \" or \" - \" or \" › ")
                        .IsFixedLength()
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_WebsiteSeoSetting_TitleSeparator");

                    b.Property<int>("WebsiteID")
                        .HasColumnType("int");

                    b.HasKey("WebsiteSeoSettingID");

                    b.HasIndex("WebsiteID");

                    b.ToTable("WebsiteSeoSetting", (string)null);
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.WebsiteSocialLink", b =>
                {
                    b.Property<int>("WebsiteSocialLinkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("SocialIcon")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SocialName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<byte>("SocialType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("UrlAddress")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("WebsiteID")
                        .HasColumnType("int");

                    b.HasKey("WebsiteSocialLinkID");

                    b.HasIndex("WebsiteID");

                    b.ToTable("WebsiteSocialLink", (string)null);
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.WebstieStorageSetting", b =>
                {
                    b.Property<int>("WebsiteStorageSettingsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AllowedExtensions")
                        .HasMaxLength(710)
                        .IsUnicode(false)
                        .HasColumnType("varchar(710)");

                    b.Property<bool>("AutoGenerateThumbnails")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("MaxFileSizeKB")
                        .HasColumnType("bigint");

                    b.Property<short>("StorageProvider")
                        .HasColumnType("smallint");

                    b.Property<string>("StorageSettingsJSON")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("WebsiteID")
                        .HasColumnType("int");

                    b.HasKey("WebsiteStorageSettingsID");

                    b.HasIndex("WebsiteID");

                    b.ToTable("WebstieStorageSettings");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.City", b =>
                {
                    b.HasOne("Dotnetable.Domain.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryID")
                        .IsRequired()
                        .HasConstraintName("FK_City_Country");

                    b.HasOne("Dotnetable.Domain.Entities.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateID")
                        .HasConstraintName("FK_City_State");

                    b.Navigation("Country");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.CityTranslation", b =>
                {
                    b.HasOne("Dotnetable.Domain.Entities.City", "City")
                        .WithMany("CityTranslations")
                        .HasForeignKey("CityID")
                        .IsRequired()
                        .HasConstraintName("FK_City_Translation_City");

                    b.Navigation("City");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.CountryTranslation", b =>
                {
                    b.HasOne("Dotnetable.Domain.Entities.Country", "Country")
                        .WithMany("CountryTranslations")
                        .HasForeignKey("CountryID")
                        .IsRequired()
                        .HasConstraintName("FK_CountryTranslation_Country");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.EmailSubscribe", b =>
                {
                    b.HasOne("Dotnetable.Domain.Entities.Member", "Member")
                        .WithMany("EmailSubscribes")
                        .HasForeignKey("MemberID")
                        .HasConstraintName("FK_EmailSubscribe_Member");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.FileRecord", b =>
                {
                    b.HasOne("Dotnetable.Domain.Entities.WebstieStorageSetting", "WebsiteStorageSettings")
                        .WithMany("FileRecords")
                        .HasForeignKey("WebsiteStorageSettingsID")
                        .IsRequired()
                        .HasConstraintName("FK_FileRecord_WebstieStorageSettings");

                    b.Navigation("WebsiteStorageSettings");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.Language", b =>
                {
                    b.HasOne("Dotnetable.Domain.Entities.Website", "Website")
                        .WithMany("Languages")
                        .HasForeignKey("WebsiteID")
                        .IsRequired()
                        .HasConstraintName("FK_Language_Website");

                    b.Navigation("Website");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.LocalizationKey", b =>
                {
                    b.HasOne("Dotnetable.Domain.Entities.Language", "Website")
                        .WithMany("LocalizationKeys")
                        .HasForeignKey("WebsiteID")
                        .IsRequired()
                        .HasConstraintName("FK_LocalizationKey_Language");

                    b.Navigation("Website");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.LocalizationValue", b =>
                {
                    b.HasOne("Dotnetable.Domain.Entities.LocalizationKey", "LocalizationKey")
                        .WithMany("LocalizationValues")
                        .HasForeignKey("LocalizationKeyID")
                        .IsRequired()
                        .HasConstraintName("FK_LocalizationValue_LocalizationKey");

                    b.Navigation("LocalizationKey");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.Member", b =>
                {
                    b.HasOne("Dotnetable.Domain.Entities.Policy", "Policy")
                        .WithMany("Members")
                        .HasForeignKey("PolicyID")
                        .IsRequired()
                        .HasConstraintName("FK_Member_Policy");

                    b.HasOne("Dotnetable.Domain.Entities.Website", "Website")
                        .WithMany("Members")
                        .HasForeignKey("WebsiteID")
                        .IsRequired()
                        .HasConstraintName("FK_Member_Website");

                    b.Navigation("Policy");

                    b.Navigation("Website");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.MemberForgetPassword", b =>
                {
                    b.HasOne("Dotnetable.Domain.Entities.Member", "Member")
                        .WithMany("MemberForgetPasswords")
                        .HasForeignKey("MemberID")
                        .IsRequired()
                        .HasConstraintName("FK_MemberForgetPassword_Member");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.PolicyRole", b =>
                {
                    b.HasOne("Dotnetable.Domain.Entities.Policy", "Policy")
                        .WithMany("PolicyRoles")
                        .HasForeignKey("PolicyID")
                        .IsRequired()
                        .HasConstraintName("FK_PolicyRole_Policy");

                    b.HasOne("Dotnetable.Domain.Entities.Role", "Role")
                        .WithMany("PolicyRoles")
                        .HasForeignKey("RoleID")
                        .IsRequired()
                        .HasConstraintName("FK_PolicyRole_Role");

                    b.Navigation("Policy");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.State", b =>
                {
                    b.HasOne("Dotnetable.Domain.Entities.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryID")
                        .IsRequired()
                        .HasConstraintName("FK_State_Country");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.StateTranslation", b =>
                {
                    b.HasOne("Dotnetable.Domain.Entities.State", "State")
                        .WithMany("StateTranslations")
                        .HasForeignKey("StateID")
                        .IsRequired()
                        .HasConstraintName("FK_StateTranslation_State");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.Website", b =>
                {
                    b.HasOne("Dotnetable.Domain.Entities.FileRecord", "FaveIconFile")
                        .WithMany("WebsiteFaveIconFiles")
                        .HasForeignKey("FaveIconFileID")
                        .HasConstraintName("FK_Website_FileRecord1");

                    b.HasOne("Dotnetable.Domain.Entities.FileRecord", "LogoFile")
                        .WithMany("WebsiteLogoFiles")
                        .HasForeignKey("LogoFileID")
                        .HasConstraintName("FK_Website_FileRecord");

                    b.Navigation("FaveIconFile");

                    b.Navigation("LogoFile");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.WebsiteIP", b =>
                {
                    b.HasOne("Dotnetable.Domain.Entities.Website", "Website")
                        .WithMany("WebsiteIPs")
                        .HasForeignKey("WebsiteID")
                        .IsRequired()
                        .HasConstraintName("FK_WebsiteIP_Website");

                    b.Navigation("Website");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.WebsiteScript", b =>
                {
                    b.HasOne("Dotnetable.Domain.Entities.Website", "Website")
                        .WithMany("WebsiteScripts")
                        .HasForeignKey("WebsiteID")
                        .IsRequired()
                        .HasConstraintName("FK_WebsiteScript_Website");

                    b.Navigation("Website");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.WebsiteSeoSetting", b =>
                {
                    b.HasOne("Dotnetable.Domain.Entities.Website", "Website")
                        .WithMany("WebsiteSeoSettings")
                        .HasForeignKey("WebsiteID")
                        .IsRequired()
                        .HasConstraintName("FK_WebsiteSeoSetting_Website");

                    b.Navigation("Website");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.WebsiteSocialLink", b =>
                {
                    b.HasOne("Dotnetable.Domain.Entities.Website", "Website")
                        .WithMany("WebsiteSocialLinks")
                        .HasForeignKey("WebsiteID")
                        .IsRequired()
                        .HasConstraintName("FK_WebsiteSocialLink_Website");

                    b.Navigation("Website");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.WebstieStorageSetting", b =>
                {
                    b.HasOne("Dotnetable.Domain.Entities.Website", "Website")
                        .WithMany("WebstieStorageSettings")
                        .HasForeignKey("WebsiteID")
                        .IsRequired()
                        .HasConstraintName("FK_WebstieStorageSettings_Website");

                    b.Navigation("Website");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.City", b =>
                {
                    b.Navigation("CityTranslations");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("CountryTranslations");

                    b.Navigation("States");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.FileRecord", b =>
                {
                    b.Navigation("WebsiteFaveIconFiles");

                    b.Navigation("WebsiteLogoFiles");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.Language", b =>
                {
                    b.Navigation("LocalizationKeys");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.LocalizationKey", b =>
                {
                    b.Navigation("LocalizationValues");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.Member", b =>
                {
                    b.Navigation("EmailSubscribes");

                    b.Navigation("MemberForgetPasswords");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.Policy", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("PolicyRoles");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.Role", b =>
                {
                    b.Navigation("PolicyRoles");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.State", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("StateTranslations");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.Website", b =>
                {
                    b.Navigation("Languages");

                    b.Navigation("Members");

                    b.Navigation("WebsiteIPs");

                    b.Navigation("WebsiteScripts");

                    b.Navigation("WebsiteSeoSettings");

                    b.Navigation("WebsiteSocialLinks");

                    b.Navigation("WebstieStorageSettings");
                });

            modelBuilder.Entity("Dotnetable.Domain.Entities.WebstieStorageSetting", b =>
                {
                    b.Navigation("FileRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
